import hashlib, time

current_time = time.time()
string_time = str(current_time)

def encode(datastring):
    sha256_hash = hashlib.sha256()
    sha256_hash.update(datastring.encode('utf-8'))
    return sha256_hash.hexdigest()

print('\nWelcome to CLI_T-Chain')
print('---------------------\n')
print("This is a simulated blockchain with manueal overrides for\nlearning purposes. Understand blockchains from behind the scenes! \nTo get started enter 'help' to show a list of commands.\n")

print('Transactions: ')
print("  John sends Jane  $20")
print("  Lizz sends Jazy  $23")
print("  Luke sends Micky $33")
print("  Kyle sends Nick  $50")
print(" ")

print("-----Block 0-----")
print(f"Timestamp            : {string_time}")
print("Transaction          : ")
print("  From               : Alice")
print("  To                 : John")
print("  Amount             : $50")
print(f"Hash                 : {encode(string_time)}")
print(f"Previous Hash        : 0000000000000000000000000000000000000000000000000000000000000000")
print("Nonce                : 42")
print("")

print("-----Block 1-----")
print(f"Timestamp            : {str(current_time + 32)}")
print("Transaction          : ")
print("  From               : James")
print("  To                 : Sally")
print("  Amount             : $30")
print(f"Hash                 : {encode(str(current_time + 32))}")
print(f"Previous Hash        : {encode(string_time)}")
print("Nonce                : 1")
print("")

print("Enter transaction details:")
print("  From      :John Doe")
print("  To        :Jane Doe")
print("  Amount    :$20")
print("\n Confirm? (yes/no)\n")

print("Editiing Block #0")
print("Current From         :John Doe")
print("Current To           :Jane Doe")
print("Current Amount       :$20")
print("")
print("New From             :Billy")
print("New To               :Sally")
print("New Amount           :$40")
print("\nConfirm change?(yes/no)")

print("")
print("Walkthroughs: ")
print("1. To add a transaction enter in 'add'.")
print("2. To edit a transactions enter in 'edit'. It'll ask for a block number afterwards.")
print("3. To see a list of transactions enter in 'home'.")
print("4. To see entire blockchain enter in 'display blockchain'.")
print("")

print("add                      -add a new transaction")
print("display blockchain       -list all blocks")
print("home                     -display homepage")
print("help                     -go to commands page")
print("edit                     -edit past transactions")
print("walkthrough              -show how to use guide")
print("switch                   -switch between hash functions SHA-1 and SHA-256")
print("")